apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: react-chinjen-de-tls
spec:
  secretName: react-chinjen-de
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: react-chinjen.de
  dnsNames:
    - react-chinjen.de
    - www.react-chinjen.de
  # acme:
  #   config:
  #     - http01:
  #         ingressClass: nginx
  #       domains:
  #         - react-chinjen.de
  #         - www.react-chinjen.de