name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker Build Test
        run: |-
          docker build -t rallycoding/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true rallycoding/react-test npm test

      # - name: Set Service Key
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     credentials_json: '${{ secrets.GKE_SA_KEY }}'

      # - name: Set Project
      #   uses: google-github-actions/setup-gcloud@v0
      #   with:
      #     project_id: sacred-alloy-391307

      # - name: Auth
      #   run: |-
      #     gcloud --quiet auth configure-docker

      # - name: Get Credentials
      #   uses: google-github-actions/get-gke-credentials@v0
      #   with:
      #     cluster_name: multi-cluster
      #     location: us-central1-c

      # - name: Build
      #   run: |-
      #     docker build -t adrianchinjen/multi-client-k8s:latest -t adrianchinjen/multi-client-k8s:${{ env.SHA }} -f ./client/Dockerfile ./client
      #     docker build -t adrianchinjen/multi-server-k8s:latest -t adrianchinjen/multi-server-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server
      #     docker build -t adrianchinjen/multi-worker-k8s:latest -t adrianchinjen/multi-worker-k8s:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      # - name: Push
      #   run: |-
      #     docker push adrianchinjen/multi-client-k8s:latest
      #     docker push adrianchinjen/multi-client-k8s:latest
      #     docker push adrianchinjen/multi-server-k8s:latest
      #     docker push adrianchinjen/multi-worker-k8s:latest

      #     docker push adrianchinjen/multi-client-k8s:${{ env.SHA }}
      #     docker push adrianchinjen/multi-server-k8s:${{ env.SHA }}
      #     docker push adrianchinjen/multi-worker-k8s:${{ env.SHA }}

      # - name: Apply
      #   run: |-
      #     kubectl apply -f k8s
      #     kubectl set image deployments/server-deployment server=adrianchinjen/multi-server-k8s:${{ env.SHA }}
      #     kubectl set image deployments/client-deployment client=adrianchinjen/multi-client-k8s:${{ env.SHA }}
      #     kubectl set image deployments/worker-deployment worker=adrianchinjen/multi-worker-k8s:${{ env.SHA }}
